### ISSUE TITLE
Where should the back button go from the CTA page?

### ISSUE THREAD

**Issue by ggordn3r** [iambateman/RankIt#40]
_from Trey: I'm not sure what the best UX is here. Thoughts?_

From a tester:

On CTA page, Pushing the back button takes me back to the very start of the RCV tabulation (the summary screen), not the final page of the round-by-round results. I expected the back button to go back to the immediately previous page.

**Comment by iambateman** [comment]
Because there are a variable number of rounds, it's safest to just send them back to the summary.

Specifically, this prevents a situation in which someone votes, and there are 7 rounds, but someone else votes, which reduces the total # of rounds to 5. You could end up in weird situations as a result.

**Comment by ggordn3r** [comment]
Thanks, that makes sense. Closing.
